version: "3.7"

services:
  db:
    image: postgres:13-alpine
    env_file:
      - ./.env.dev
    volumes:
      - pg_data:/var/lib/postgresql/data/
  django:
    container_name: crud_rest
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash "./prestart.sh"
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A crud_rest worker -l INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - django
  dashboard:
    build: .
    command: celery -A crud_rest flower
    ports:
      - "5555:5555"
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - redis
      - celery
volumes:
  pg_data:
