version: "3.7"

services:
  db:
    image: postgres:13-alpine
    env_file:
      - ./.env.dev
    volumes:
      - pg_data:/var/lib/postgresql/data/
  django:
    container_name: crud_rest
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/app/manage.py migrate --noinput &&
                      python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: celery -A crud_rest worker -l INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - django
  dashboard:
    build: .
    command: celery flower --port=5566
    ports:
      - 5555:5555
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - redis
      - celery
volumes:
  pg_data:
